### PR TITLE
SQLiteReporter tests

### PR DESCRIPTION
**Pull request by Quolyk**
#53

### CODE REVIEW

**Comment by Quolyk** [comment]
I deleted quotes from `'__ZTIN4llvm20SectionMemoryManagerE'` to correctly write to db. I don't now if I'm on the right way

**Comment by AlexDenisov** [comment]
The right way would be to use the same approach as used in another place: not putting string directly into sql query, but using `?` + prepare statement + bind_text.
Please look at `insertMutationExecutionResultSQL` for a reference.

**Comment by Quolyk** [comment]
I guess, now it's working

**Comment by AlexDenisov** [comment]
Thanks a lot, @Quolyk. Could you please squash commits before the merge?
https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by Quolyk** [comment]
@AlexDenisov, Done

**Comment by AlexDenisov** [comment]
You've solved really annoying problem, thanks a lot for your effort :)

**Pull request merged**
