### PR TITLE
Apache License 2.0.

### PR DESCRIPTION
**Pull request by stanislaw**
#76

### CODE REVIEW

**Comment by stanislaw** [comment]
@JDevlieghere @Quolyk we are going to set the license to Apache v2. Since you have made your contributions in times when no license was in place we have to ask you explicitly as copyright holders of your work if you are fine with this change.

**Comment by JDevlieghere** [comment]
Of course! Please consider this my explicit approval to relicense my contributions under the Apache v2 license.

**Comment by Quolyk** [comment]
I'm fine with the Apache v2 license.

**Comment by stanislaw** [comment]
Thanks @JDevlieghere @Quolyk !

**Pull request merged**
