### PR TITLE
CPack: do not error on unknown OS; mull-cxx: support shared libLLVM

### PR DESCRIPTION
**Pull request by myfreeweb**
Fixes the following error:

```
CMake Error at cmake/cpack.cmake:47 (if):
  if given arguments:

    "STREQUAL" "macOS"

  Unknown arguments specified
```

### CODE REVIEW

**Comment by AlexDenisov** [comment]
FreeBSD, I suppose? :)

**Comment by myfreeweb** [comment]
Yes

**Comment by AlexDenisov** [comment]
Thanks a lot for the fix, I'll merge on green.
jfyi, there is an (empty) issue for the FreeBSD package #449.

**Comment by myfreeweb** [comment]
Also fixed an over-linking issue: `mull-cxx` would get linked to both `libLLVM-8.so` and various static libs (`libLLVMCore.a` etc.) which would cause it not to work:

```
: CommandLine Error: Option 'print-summary-global-ids' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

(https://github.com/AlexDenisov/LibEBC/pull/2 is part of that too)

**Comment by myfreeweb** [comment]
(btw, `llvm_config(target USE_SHARED Core Support Whatever…)` automatically handles shared vs static, but I don't know if you have any reasons to do it manually and I don't know if it's available on old LLVMs)

**Comment by AlexDenisov** [comment]
Good catch.

> (btw, llvm_config(target USE_SHARED Core Support Whatever…) automatically handles shared vs static, but I don't know if you have any reasons to do it manually and I don't know if it's available on old LLVMs)

Does it use `llvm-config` binary under the hood? We had some troubles with it in the past, e.g. linking order of clang libraries. Other than that - current build system is something that somehow works, it was not properly engineered, but rather evolved with time.

**Comment by myfreeweb** [comment]
No, it's a small wrapper around `llvm_map_components_to_libnames`. Nothing in `lib/cmake` actually seems to call `llvm-config`.

**Pull request merged**
