### PR TITLE
Enable more detailed coverage

### PR DESCRIPTION
**Pull request by m42e**
This enables branch based coverage elimination.
Please check if this matches your expectation. I would suggest to have an additional switch to enable the line based coverage as it is quite a break in the behaviour compared to the current one.

Let me know what you think.

### CODE REVIEW

**Comment by AlexDenisov** [comment]
It's ok to break the current behavior, but I'd strongly recommend adding/extending the suite to reflect the changes.

**Comment by m42e** [comment]
For sure, but just wanted some ok before doing so.

**Comment by m42e** [comment]
I had something prepared (manual testing so far) but should confirm it is working.

**Comment by m42e** [comment]
while scrolling through the code, would you consider something like this more clear @AlexDenisov:

```c++
bool FunctionUnderTest::isCovered(const SourceLocation& location) const {
  if (linecoverage.size() == 0){
    return covered;
  }
  bool iscovered = true;
  auto after_start = [&location](auto LineStart, auto ColumnStart){
    return (LineStart < location.line || (LineStart == location.line && ColumnStart <= location.column));
  };
  auto before_end = [&location](auto LineEnd, auto ColumnEnd){
    return (LineEnd > location.line || (LineEnd == location.line && ColumnEnd >= location.column));
  };
  for_each(linecoverage.begin(), linecoverage.end(), [&](const auto & cov){
    if (after_start(cov.LineStart, cov.ColumnStart) && before_end(cov.LineEnd, cov.ColumnEnd)){
      iscovered &= cov.ExecutionCount > 0;
    }
  });
  return iscovered;
}

```

**Pull request merged**
