### PR TITLE
Automatically deploy packages for Ubuntu and macOS

### PR DESCRIPTION
**Pull request by AlexDenisov**
How to install nightly builds of mull:

Add new apt repo:
```
sudo echo "deb https://dl.bintray.com/mull-project/ubuntu nightly main" >> /etc/apt/sources.list
```
Add the bintray GPG key:
```
wget https://bintray.com/user/downloadSubjectPublicKey?username=bintray -O bintray.key
sudo apt-key add bintray.key
```
Update index & install mull:
```
sudo apt-get update
sudo apt-get install mull
```
Run mull:
```
mull-cxx --version
```

### CODE REVIEW

**Comment by stanislaw** [comment]
Testing this from Ubuntu Docker image:

All steps are working except these two points:

1) After the `sudo apt-key add bintray.key` step:

```
$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://dl.bintray.com/mull-project/ubuntu/dists/nightly/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Had to run this:

```
root@54d46782d0a0:/app# apt install apt-transport-https
```

2) Then I am getting this:

```
root@54d46782d0a0:/app# mull-cxx --version
mull-cxx: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by mull-cxx)
mull-cxx: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by mull-cxx)
```

**Comment by AlexDenisov** [comment]
Fair enough! I built the packages on Ubuntu 18.04, but now I also added Ubuntu 16.04.

Now, the repos are:
```
deb https://dl.bintray.com/mull-project/ubuntu-16 nightly main
deb https://dl.bintray.com/mull-project/ubuntu-18 nightly main
```

You can try that as soon as the PR gets green @stanislaw.

**Comment by stanislaw** [comment]
I can confirm that it now works on my end!

```
root@d67ba8a23c4f:/app# mull-cxx -version
Mull: LLVM-based mutation testing
https://github.com/mull-project/mull
Version: 0.6.1.676
Commit: cf0de03
Date: 14 Mar 2020
LLVM: 8.0.0
```

And it is an amazing workflow!

**Comment by AlexDenisov** [comment]
Hi @chgans, in one of the issues you mentioned that you compile Mull from sources yourself.

I'd appreciate it if you can give a try to this distribution mechanism and share some feedback.
Here are the right instructions that should work as is (assuming you are on Ubuntu 18):
```
sudo echo "deb https://dl.bintray.com/mull-project/ubuntu-18 nightly main" >> /etc/apt/sources.list
wget https://bintray.com/user/downloadSubjectPublicKey?username=bintray -O bintray.key
sudo apt-key add bintray.key
sudo apt-get update
sudo apt-get install mull
mull-cxx --version
```
You should see something like `Version: 0.6.1-trunk4242`.

**Pull request merged**
