### PR TITLE
Remove mull-cxx from tests

### PR DESCRIPTION
**Pull request by AlexDenisov**
Related #945

### CODE REVIEW

**Comment by ta0wang** [comment]
Hello, I got in truble with the operation of mull-cxx remove. I have a test program need to run with a command-line argument, used as the "[Non-standard test suites](https://mull.readthedocs.io/en/0.16.0/tutorials/NonStandardTestSuite.html#)". After this remove, how can i make it? Looking forward to your answer, Thanks!

**Comment by AlexDenisov** [comment]
@ta0wang I will be updating the tutorials soon, but in short: the first step should be replaced with the IR frontend, as described here https://mull.readthedocs.io/en/0.16.0/tutorials/HelloWorld.html
Please let me know if it doesn't work for you!

**Comment by ta0wang** [comment]
> @ta0wang I will be updating the tutorials soon, but in short: the first step should be replaced with the IR frontend, as described here https://mull.readthedocs.io/en/0.16.0/tutorials/HelloWorld.html Please let me know if it doesn't work for you!

Thanks for your reply! @AlexDenisov 
It's running OK with the IR frontend if my test has no argument input!

> ./mull-runner-12 -ide-reporter-show-killed ./mytest   ->  It's running OK.
> ./mull-runner-12 -ide-reporter-show-killed ./mytest --gtest-filter=Test.t1  ->  not OK with gtest-filter argument.

I used "[Non-standard test suites](https://mull.readthedocs.io/en/0.16.0/tutorials/NonStandardTestSuite.html#)" mode in the old version, with python script to take parameters. `subprocess.run(["mytest", "--gtest-filter=Test.t1"], check=True)`

Can I make it with IR frontend or some other? Thanks!

**Comment by ta0wang** [comment]
@AlexDenisov I have another question,

If the '.out' test program run through loading a dynamic object, and the real object under test is the dynamic object instead of the '.out'. 
Can mutations still working? if I compile and link the dynamic object with '-fexperimental-new-pass-manager -fpass-plugin=/usr/local/lib/mull-ir-frontend-12 -g -grecord-command-line', but the '.out' not contain the compile options.

Maybe, I need to have a try!

**Comment by AlexDenisov** [comment]
@ta0wang give it a try and consider opening a separate issue, otherwise it is easy to miss your questions here.

---

> ./mull-runner-12 -ide-reporter-show-killed ./mytest1 --gtest-filter=Test.t1 -> not OK with gtest-filter argument.

Take a look at this tutorial https://mull.readthedocs.io/en/latest/tutorials/NonStandardTestSuite.html

**Comment by ta0wang** [comment]
> @ta0wang give it a try and consider opening a separate issue, otherwise it is easy to miss your questions here.
> 
> > ./mull-runner-12 -ide-reporter-show-killed ./mytest1 --gtest-filter=Test.t1 -> not OK with gtest-filter argument.
> 
> Take a look at this tutorial https://mull.readthedocs.io/en/latest/tutorials/NonStandardTestSuite.html

@AlexDenisov Thanks! I will have a try, If any other questions, I wil open a separate issue!

**Pull request merged**
