### PR TITLE
Add CppUTest support

### PR DESCRIPTION
**Pull request by OMantere**
This PR adds support for the CppUTest test framework (http://cpputest.github.io)

### CODE REVIEW

**Comment by AlexDenisov** [comment]
Hi @OMantere, thanks for the PR. There are some weird failures I'm trying to debug right now. What I see is that CppUTest re-defines operators `new/delete` which interferes with LLVM memory management. I'll try to find the fix for this issue, but if you have any ideas/suggestions - do not hesitate to share them :)

**Comment by AlexDenisov** [comment]
All right, the memory leak thing can be disabled with the following change:
```diff
diff --git a/vendor/CMakeLists.txt b/vendor/CMakeLists.txt
index 0f1d1b7..971d486 100644
--- a/vendor/CMakeLists.txt
+++ b/vendor/CMakeLists.txt
@@ -1,3 +1,7 @@
 add_subdirectory(json11 EXCLUDE_FROM_ALL)
 add_subdirectory(LibEBC EXCLUDE_FROM_ALL)
+
 add_subdirectory(cpputest EXCLUDE_FROM_ALL)
+target_compile_definitions(CppUTest
+  PRIVATE CPPUTEST_MEM_LEAK_DETECTION_DISABLED
+)
```

This should make CI green, and we'll be ready for merge.

**Comment by OMantere** [comment]
@AlexDenisov Thanks for the change! I applied it in commit `72b7dc0`.

**Review by AlexDenisov — APPROVED** [review]
🎉

**Comment by AlexDenisov** [comment]
CI is off again, but I'll fix it separately.

**Pull request merged**
