### PR TITLE
[WIP] Fix and add GoogleTestFinder tests

### PR DESCRIPTION
**Pull request by Quolyk**
#72
The issue is frozen until I find a way to enable disabled tests in `GoogleTestFinderTests`

### CODE REVIEW

**Comment by stanislaw** [comment]
@Quolyk any updates here? We are fine with picking your commits and finishing the work just in case.

**Comment by Quolyk** [comment]
No updates here. All commits are in `master` already. This pull request can be closed. If not finished I will return to this issue as soon as I can.

**Comment by stanislaw** [comment]
@Quolyk you mentioned:

> The issue is frozen until I find a way to enable disabled tests in GoogleTestFinderTests

We still have `YOU HAVE 2 DISABLED TESTS`. Let me know if you are going to continue with this. Also make sure to rebase and squash this branch against master so that we see the actual diff.

**Comment by stanislaw** [comment]
Closed via #131 .

**Pull request closed without merging**
