### PR TITLE
Patch reporter

### PR DESCRIPTION
**Pull request by m42e**
Solves https://github.com/mull-project/mull/issues/587
Hope this helps to get closet to V1.0 (https://github.com/mull-project/mull/issues/775)

### CODE REVIEW

**Comment by m42e** [comment]
Suggestion: use `--git-project-root` as base directory. What do you think? @stanislaw  @AlexDenisov

**Comment by AlexDenisov** [comment]
Thank you so much for bringing this up! This is certainly a great start!

Could you add some test cases for some mutation operators? In particular, the interesting operators are `cxx_lshift_to_rshift`, `cxx_lt_to_ge`, `cxx_le_to_lt` (at least).

The other important one is `cxx_remove_void_call`, but I don't think it's possible to get it right without actually parsing the source code.

> Suggestion: use --git-project-root as base directory. What do you think?

What is the base directory in this context?

**Comment by m42e** [comment]
Ok, will do i can add some sample files, too. 

Base path means the Path the patch should be relative to. For now it is absolute.

**Comment by m42e** [comment]
The test should use simply Google test or is there another way these check should be done?

**Comment by AlexDenisov** [comment]
There are integration tests based on LLVM lit and filecheck under `tests-lit` directory, I'd recommend adding the tests there.

**Comment by AlexDenisov** [comment]
Oh, and the git root sounds good as a base path!

**Comment by m42e** [comment]
> Oh, and the git root sounds good as a base path!

I decided to use the git path as fallback for `mull-cxx` and added an extra command line parameter, as `mull-runner` does not have the `git-project-dir` option. Feel free to suggest otherwise. But I think it might be a bit misleading in the `mull-runner` context if the `git-project-dir` is not used otherwise.

**Comment by AlexDenisov** [comment]
Just played around with it locally and it looks pretty good!
We'll need to mention somewhere that it only works for single-line changes (i.e. multiline patches won't work correctly) and that some mutators may produce invalid code (at least `cxx_init_const` and `negate_mutator` don't work properly).

All in all, looks good and I'm happy to merge unless you want to add something :)

**Comment by m42e** [comment]
Feel free to merge. Also feel free to send me examples of what’s not working an I will have a look at it.

**Comment by AlexDenisov** [comment]
> Also feel free to send me examples of what’s not working an I will have a look at it.

`cxx_const_init` doesn't work properly with [the hello-world example](https://mull.readthedocs.io/en/latest/tutorials/HelloWorld.html).
`remove_void_function` produces incorrect diff for something like
```c
void foo(...);
///
foo(a,
      b);
```
and I guess
```c
void foo();
void bar();
///
foo(); bar();
```
will also be incorrect.

All in all, there is no straightforward way to handle this at the moment: we need to attach certain metadata to some mutation points.

**Comment by m42e** [comment]
@AlexDenisov I tried the `cxx_init_const` and I think it is actually the replacement information or the source location information that is not correct. It is also not displayed correctly using the `Elements` reporter.

The multiline does not work, that's sadly true, fix is here: #913

the third example works just fine.

**Pull request merged**
