### PR TITLE
Multiline patch fix

### PR DESCRIPTION
**Pull request by m42e**
fix issue with multiline patch generation

### CODE REVIEW

**Comment by m42e** [comment]
CI Ubuntu 20.04 / LLVM 12.0 (pull_request) Failing after 3m — LLVM 12.0 fails due to a llvm download issue :(

**Comment by AlexDenisov** [comment]
@m42e I just realized that may not have enough permissions to restart the job yourself. I just restarted it, but it fails again, let's rebase/merge main this branch to pick up #916.

**Comment by AlexDenisov** [comment]
I should've merged this earlier to prevent conflict 😞

**Comment by AlexDenisov** [comment]
Thank you once again @m42e! Let's get the rest of the patches in and I'll cut the new release as there are lots of goods on `main`!

**Pull request merged**
