### PR TITLE
Enable LIT tests on CI for Linux

### LINKED ISSUE #715: Enable LIT tests on CI for Linux
Currently, LIT tests are only run on macOS.

### PR DESCRIPTION
**Pull request by stanislaw**
- [x] pip3 is missing in Ubuntu Linux playbook
- [x] `[warning] Could not find dynamic library: libstdc++.so.6`
- [x] `error: no member named 'abort' in namespace 'std'`

And after the libc fix:

- [x] `[warning] Could not find dynamic library: libc++.so.1`

Closes #715

### CODE REVIEW

**Comment by stanislaw** [comment]
The current issue on Linux is exactly the one that was reported in #528 .

Adding the following Mull flags fixes this for me in Docker built with our provisioning files:

```
mull ... -ld-search-path=/usr/lib/x86_64-linux-gnu -ld-search-path=/lib/x86_64-linux-gnu ...
```

based on the following paths:

```
root@7f0e40e2d86e:/opt/build.mull.release.dir# ldd ../mull/tests-lit/tests/white-ast-search/scalar/01_return_value/sample.cpp.exe
	linux-vdso.so.1 =>  (0x00007fff3f9fc000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc1f7325000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc1f701c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc1f6e06000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc1f6a3c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc1f76a7000)
```

--- 

The easiest solution I see would be to switch to using the %mull variable where we would mix in the portable flags or introduce another %mull-portable-flags variable where we would put this `-ld-search-path` stuff.

@AlexDenisov let me know what you think.

**Comment by AlexDenisov** [comment]
The easiest solution would be to add those flags as is. Currently, they only effective on Linux, so adding other configuration options might be an overkill for this situation.

**Comment by stanislaw** [comment]
> The easiest solution would be to add those flags as is.

What do you mean exactly?

Keep in mind that we have to do this in each and every lit test, this is why I am thinking of abstracting them with a variable like `%mull-portable-flags` in `lit.cfg`.

**Comment by AlexDenisov** [comment]
> What do you mean exactly?

```
mull ... -ld-search-path=/usr/lib/x86_64-linux-gnu -ld-search-path=/lib/x86_64-linux-gnu ...
```

> Keep in mind that we have to do this in each and every lit test, this is why I am thinking of abstracting them with a variable like %mull-portable-flags in lit.cfg.

I think it should rather belong to the test, and not to the 'global' setup. But I don't mind if you put it into the config file, you decide.

**Comment by stanislaw** [comment]
OMG!

**Pull request merged**
